### ISSUE TITLE
Cannot run program "broccoli": CreateProcess error=2, can you please help to check?

### ISSUE THREAD

**Issue by skanel** [bianjp/blog-spring#2]
@ssbianjp  can help me to check , when I run you source code blog built with spring-boot, I got the following error:
Caused by: java.io.IOException: Cannot run program "broccoli": CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[?:1.8.0_181]
        at com.bianjp.blog.config.BroccoliServer.start(BroccoliServer.java:43) ~[main/:?]
        ... 23 more

**Comment by bianjp** [comment]
Make sure you have installed broccoli-cli.

**Comment by skanel** [comment]
yes , I have here the output when I run the command

> E:\DL\blog-spring-master>broccoli
> Usage: broccoli [options] <command> [<args ...>]
> 
> Options:
>   -V, --version               output the version number
>   -h, --help                  output usage information
> 
> Commands:
>   serve|s [options]           start a broccoli server
>   build|b [options] [target]  output files to target directory

**Comment by skanel** [comment]
and here the full output when I ran the command grandlew
E:\DL\blog-spring-master>gradlew bootRun

> Task :bootRun

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.2.RELEASE)

2019-04-11 02:10:49.806  INFO 5964 --- [  restartedMain] c.b.b.Application                        : Starting Application on AHOLTP0231 with PID 5964 (E:\DL\blog-spring-master\build\classes\java\main started by Kanel.Soeng in E:\DL\blog-spring-master)
2019-04-11 02:10:49.814  INFO 5964 --- [  restartedMain] c.b.b.Application                        : The following profiles are active: assets,development
2019-04-11 02:10:49.907  INFO 5964 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2019-04-11 02:10:49.908  INFO 5964 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2019-04-11 02:10:51.851  INFO 5964 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2019-04-11 02:10:51.855  INFO 5964 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2019-04-11 02:10:52.057  INFO 5964 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 195ms. Found 3 repository interfaces.
2019-04-11 02:10:53.066  INFO 5964 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$10d754a4] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-04-11 02:10:53.478  INFO 5964 --- [  restartedMain] o.e.j.u.log                              : Logging initialized @5455ms to org.eclipse.jetty.util.log.Slf4jLog
2019-04-11 02:10:53.882  INFO 5964 --- [  restartedMain] o.s.b.w.e.j.JettyServletWebServerFactory : Server initialized with port: 8080
2019-04-11 02:10:53.890  INFO 5964 --- [  restartedMain] o.e.j.s.Server                           : jetty-9.4.14.v20181114; built: 2018-11-14T21:20:31.478Z; git: c4550056e785fb5665914545889f21dc136ad9e6; jvm 1.8.0_181-b13
2019-04-11 02:10:53.928  INFO 5964 --- [  restartedMain] o.e.j.s.h.C.application                  : Initializing Spring embedded WebApplicationContext
2019-04-11 02:10:53.928  INFO 5964 --- [  restartedMain] o.s.w.c.ContextLoader                    : Root WebApplicationContext: initialization completed in 4020 ms
2019-04-11 02:10:55.258  INFO 5964 --- [  restartedMain] o.e.j.s.session                          : DefaultSessionIdManager workerName=node0
2019-04-11 02:10:55.259  INFO 5964 --- [  restartedMain] o.e.j.s.session                          : No SessionScavenger set, using defaults
2019-04-11 02:10:55.261  INFO 5964 --- [  restartedMain] o.e.j.s.session                          : node0 Scavenging every 660000ms
2019-04-11 02:10:55.278  INFO 5964 --- [  restartedMain] o.e.j.s.h.ContextHandler                 : Started o.s.b.w.e.j.JettyEmbeddedWebAppContext@18ecb3ae{application,/,[file:///C:/Users/Kanel.Soeng.AMKCAMBODIA/AppData/Local/Temp/jetty-docbase.5971759208754253821.8080/],AVAILABLE}
2019-04-11 02:10:55.279  INFO 5964 --- [  restartedMain] o.e.j.s.Server                           : Started @7259ms
2019-04-11 02:10:55.368  INFO 5964 --- [  restartedMain] o.f.c.i.l.VersionPrinter                 : Flyway Community Edition 5.2.4 by Boxfuse
2019-04-11 02:10:55.386  INFO 5964 --- [  restartedMain] c.z.h.HikariDataSource                   : HikariPool-1 - Starting...
2019-04-11 02:10:55.682  INFO 5964 --- [  restartedMain] c.z.h.HikariDataSource                   : HikariPool-1 - Start completed.
2019-04-11 02:10:55.690  INFO 5964 --- [  restartedMain] o.f.c.i.d.DatabaseFactory                : Database: jdbc:postgresql://localhost/blog_development (PostgreSQL 10.7)
2019-04-11 02:10:55.941  INFO 5964 --- [  restartedMain] o.f.c.i.c.DbValidate                     : Successfully validated 2 migrations (execution time 00:00.051s)
2019-04-11 02:10:56.039  INFO 5964 --- [  restartedMain] o.f.c.i.s.JdbcTableSchemaHistory         : Creating Schema History table: "public"."flyway_schema_history"
2019-04-11 02:10:56.583  INFO 5964 --- [  restartedMain] o.f.c.i.c.DbMigrate                      : Current version of schema "public": << Empty Schema >>
2019-04-11 02:10:56.585  INFO 5964 --- [  restartedMain] o.f.c.i.c.DbMigrate                      : Migrating schema "public" to version 1 - init
2019-04-11 02:10:56.589  INFO 5964 --- [  restartedMain] o.f.c.i.s.DefaultSqlScriptExecutor       : DB: table "post" does not exist, skipping
2019-04-11 02:10:56.619  INFO 5964 --- [  restartedMain] o.f.c.i.s.DefaultSqlScriptExecutor       : DB: table "user" does not exist, skipping
2019-04-11 02:10:56.646  INFO 5964 --- [  restartedMain] o.f.c.i.c.DbMigrate                      : Migrating schema "public" to version 2 - create tag table
2019-04-11 02:10:56.648  INFO 5964 --- [  restartedMain] o.f.c.i.s.DefaultSqlScriptExecutor       : DB: table "tag" does not exist, skipping
2019-04-11 02:10:56.662  INFO 5964 --- [  restartedMain] o.f.c.i.s.DefaultSqlScriptExecutor       : DB: table "post_tag" does not exist, skipping
2019-04-11 02:10:56.688  INFO 5964 --- [  restartedMain] o.f.c.i.c.DbMigrate                      : Successfully applied 2 migrations to schema "public" (execution time 00:00.651s)
2019-04-11 02:10:56.911  INFO 5964 --- [  restartedMain] o.h.j.i.u.LogHelper                      : HHH000204: Processing PersistenceUnitInfo [
        name: default
        ...]
2019-04-11 02:10:57.072  INFO 5964 --- [  restartedMain] o.h.Version                              : HHH000412: Hibernate Core {5.3.7.Final}
2019-04-11 02:10:57.075  INFO 5964 --- [  restartedMain] o.h.c.Environment                        : HHH000206: hibernate.properties not found
2019-04-11 02:10:57.319  INFO 5964 --- [  restartedMain] o.h.a.c.Version                          : HCANN000001: Hibernate Commons Annotations {5.0.4.Final}
2019-04-11 02:10:57.596  INFO 5964 --- [  restartedMain] o.h.d.Dialect                            : HHH000400: Using dialect: org.hibernate.dialect.PostgreSQL95Dialect
2019-04-11 02:10:57.763  INFO 5964 --- [  restartedMain] o.h.e.j.e.i.LobCreatorBuilderImpl        : HHH000424: Disabling contextual LOB creation as createClob() method threw error : java.lang.reflect.InvocationTargetException
2019-04-11 02:10:57.772  INFO 5964 --- [  restartedMain] o.h.t.BasicTypeRegistry                  : HHH000270: Type registration [java.util.UUID] overrides previous : org.hibernate.type.UUIDBinaryType@1d43cd94
2019-04-11 02:11:05.735  INFO 5964 --- [  restartedMain] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2019-04-11 02:11:07.654  INFO 5964 --- [  restartedMain] o.s.s.w.DefaultSecurityFilterChain       : Creating filter chain: any request, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@47f98a38, org.springframework.security.web.context.SecurityContextPersistenceFilter@20bf446, org.springframework.security.web.header.HeaderWriterFilter@61a27bd, org.springframework.security.web.authentication.logout.LogoutFilter@5bb47f07, org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter@f38f0d4, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@7757c9aa, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@439a5cf7, org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter@67a4300d, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@5090d0a1, org.springframework.security.web.session.SessionManagementFilter@48543e27, org.springframework.security.web.access.ExceptionTranslationFilter@114edf66, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@25b2d84a]
2019-04-11 02:11:08.060  INFO 5964 --- [  restartedMain] o.s.s.c.ThreadPoolTaskExecutor           : Initializing ExecutorService 'applicationTaskExecutor'
2019-04-11 02:11:08.888  INFO 5964 --- [  restartedMain] i.l.c.EpollProvider                      : Starting without optional epoll library
2019-04-11 02:11:08.891  INFO 5964 --- [  restartedMain] i.l.c.KqueueProvider                     : Starting without optional kqueue library
2019-04-11 02:11:09.553  INFO 5964 --- [  restartedMain] o.s.b.a.e.w.EndpointLinksResolver        : Exposing 17 endpoint(s) beneath base path '/actuator'
2019-04-11 02:11:09.676  INFO 5964 --- [  restartedMain] o.s.b.d.a.OptionalLiveReloadServer       : LiveReload server is running on port 35729
2019-04-11 02:11:10.320  INFO 5964 --- [  restartedMain] s.a.ScheduledAnnotationBeanPostProcessor : No TaskScheduler/ScheduledExecutorService bean found for scheduled processing
2019-04-11 02:11:10.340  INFO 5964 --- [  restartedMain] o.e.j.s.h.C.application                  : Initializing Spring DispatcherServlet 'dispatcherServlet'
2019-04-11 02:11:10.341  INFO 5964 --- [  restartedMain] o.s.w.s.DispatcherServlet                : Initializing Servlet 'dispatcherServlet'
2019-04-11 02:11:10.358  INFO 5964 --- [  restartedMain] o.s.w.s.DispatcherServlet                : Completed initialization in 17 ms
2019-04-11 02:11:10.399  INFO 5964 --- [  restartedMain] o.e.j.s.AbstractConnector                : Started ServerConnector@14ec653c{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2019-04-11 02:11:10.402  INFO 5964 --- [  restartedMain] o.s.b.w.e.j.JettyWebServer               : Jetty started on port(s) 8080 (http/1.1) with context path '/'
2019-04-11 02:11:10.407  INFO 5964 --- [  restartedMain] c.b.b.Application                        : Started Application in 21.395 seconds (JVM running for 22.386)
java.io.IOException: Cannot run program "broccoli": CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.bianjp.blog.config.BroccoliServer.start(BroccoliServer.java:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:259)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:179)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:142)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:398)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:355)
        at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:105)
        at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:78)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:332)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
        at com.bianjp.blog.Application.main(Application.java:17)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 24 more
2019-04-11 02:11:10.438 ERROR 5964 --- [  restartedMain] o.s.b.SpringApplication                  : Application run failed

java.lang.RuntimeException: java.io.IOException: Cannot run program "broccoli": CreateProcess error=2, The system cannot find the file specified
        at com.bianjp.blog.config.BroccoliServer.start(BroccoliServer.java:46) ~[main/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:259) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:179) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:142) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:398) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:355) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:105) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:78) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:332) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
        at com.bianjp.blog.Application.main(Application.java:17) [main/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-2.1.2.RELEASE.jar:2.1.2.RELEASE]
Caused by: java.io.IOException: Cannot run program "broccoli": CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[?:1.8.0_181]
        at com.bianjp.blog.config.BroccoliServer.start(BroccoliServer.java:43) ~[main/:?]
        ... 23 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method) ~[?:1.8.0_181]
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386) ~[?:1.8.0_181]
        at java.lang.ProcessImpl.start(ProcessImpl.java:137) ~[?:1.8.0_181]
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ~[?:1.8.0_181]
        at com.bianjp.blog.config.BroccoliServer.start(BroccoliServer.java:43) ~[main/:?]
        ... 23 more

2019-04-11 02:11:10.470  INFO 5964 --- [  restartedMain] o.s.s.c.ThreadPoolTaskExecutor           : Shutting down ExecutorService 'applicationTaskExecutor'
2019-04-11 02:11:10.474  INFO 5964 --- [  restartedMain] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2019-04-11 02:11:10.478  INFO 5964 --- [  restartedMain] c.z.h.HikariDataSource                   : HikariPool-1 - Shutdown initiated...
2019-04-11 02:11:10.491  INFO 5964 --- [  restartedMain] c.z.h.HikariDataSource                   : HikariPool-1 - Shutdown completed.
2019-04-11 02:11:11.637  INFO 5964 --- [  restartedMain] o.e.j.s.AbstractConnector                : Stopped ServerConnector@14ec653c{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2019-04-11 02:11:11.637  INFO 5964 --- [  restartedMain] o.e.j.s.session                          : node0 Stopped scavenging
2019-04-11 02:11:11.639  INFO 5964 --- [  restartedMain] o.e.j.s.h.C.application                  : Destroying Spring FrameworkServlet 'dispatcherServlet'
2019-04-11 02:11:11.640  INFO 5964 --- [  restartedMain] o.e.j.s.h.ContextHandler                 : Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@18ecb3ae{application,/,[file:///C:/Users/Kanel.Soeng.AMKCAMBODIA/AppData/Local/Temp/jetty-docbase.5971759208754253821.8080/],UNAVAILABLE}

> Task :bootRun FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bootRun'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_181\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
3 actionable tasks: 1 executed, 2 up-to-date

**Comment by bianjp** [comment]
Seems that this is caused by `ProcessBuilder` does not respect the PATHEXT variable on Windows. https://stackoverflow.com/questions/40503074/how-to-run-npm-command-in-java-using-process-builder

Try changing the `broccoli` command to `broccoli.cmd` to see whether it will work.

`src/main/java/com/bianjp/blog/config/BroccoliServer.java`:

```java
  @EventListener(ApplicationReadyEvent.class)
  public void start() {
    ProcessBuilder processBuilder =
        new ProcessBuilder(
            "broccoli.cmd",
            "serve",
            "--host",
            broccoliConfig.getHost(),
            "--port",
            Integer.toString(broccoliConfig.getPort()));
    processBuilder.redirectOutput(ProcessBuilder.Redirect.INHERIT);
    processBuilder.redirectError(ProcessBuilder.Redirect.INHERIT);
    try {
      process = processBuilder.start();
    } catch (IOException e) {
      throw new RuntimeException(e);
    }
  }
```

**Comment by skanel** [comment]
perfectly works, thank so much!
